### ISSUE TITLE
Yarn 2 issues, @vue/test-utils tried to access @vue/compiler-dom

### ISSUE THREAD

**Issue by miii** [vuejs/vue-test-utils-next#245]
`@vue/compiler-dom` is not listed as a dependency which causes Yarn 2 to break.
```
@vue/test-utils tried to access @vue/compiler-dom, but it isn't declared in its dependencies;
This makes the require call ambiguous and unsound.
```
https://github.com/vuejs/vue-test-utils-next/blob/8a1f348969ffadfe1b35de746f0c27c020ee074c/src/utils/compileSlots.ts#L1

Temporary solution:
```yaml
# <project root>/.yarnrc.yml
packageExtensions:
  "@vue/test-utils@2.*":
    dependencies:
      "@vue/compiler-dom": "*"
```
